replicaCount: 3

image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi

serviceAccount:
  create: true
  annotations:
    example.com/annotation-key: "annotation-value"

ingress:
  enabled: true
  service:
    port: 80

autoscaling:
  enabled: true  # Enable autoscaling

  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 1 # Maximum number of replicas

  targetCPUUtilizationPercentage: 50  # Target CPU utilization percentage for autoscaling
  targetMemoryUtilizationPercentage: 70  # Target memory utilization percentage for autoscaling
